# Generated by Django 2.2.6 on 2019-11-04 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compositions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Состав ингредиента',
                'verbose_name_plural': 'Состав ингредиентов',
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.CreateModel(
            name='RecipesCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Категория рецепта',
                'verbose_name_plural': 'Категория рецепта',
            },
        ),
        migrations.CreateModel(
            name='RecipesToIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='процент ввода ингредиента', max_digits=4, null=True, verbose_name='процент ввода')),
                ('ingredients', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recipes.Ingredients')),
                ('recipes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recipes.Recipes')),
            ],
            options={
                'verbose_name': 'Ингредиент рецепта',
                'verbose_name_plural': 'Ингредиенты рецепта',
            },
        ),
        migrations.AddField(
            model_name='recipes',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recipes.RecipesCategory', verbose_name='Категория норматива'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='ingredients',
            field=models.ManyToManyField(through='recipes.RecipesToIngredients', to='recipes.Ingredients'),
        ),
        migrations.CreateModel(
            name='IngredientsToCompositions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='процент ввода ингредиента', max_digits=5, null=True, verbose_name='процент ввода')),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recipes.Compositions', verbose_name='Состав')),
                ('ingredients', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recipes.Ingredients', verbose_name='Ингредиенты')),
            ],
            options={
                'verbose_name': 'Состав ингредиентов',
                'verbose_name_plural': 'Состав ингредиентов',
            },
        ),
        migrations.AddField(
            model_name='ingredients',
            name='compositions',
            field=models.ManyToManyField(through='recipes.IngredientsToCompositions', to='recipes.Compositions'),
        ),
    ]
