# Generated by Django 2.2.6 on 2019-11-15 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20191112_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='slug',
            field=models.SlugField(default='asdasdas-sadas', unique=True),
            preserve_default=False,
        ),
    ]
